### ISSUE TITLE
Request: Diffraction simulator - display of reciprocal distance

### ISSUE THREAD

**Issue by rbtrrnss** [seto77/ReciPro#21]
In the diffraction simulator, would it be possible to add the display of the reciprocal distances of the diffraction spots?
![image](https://github.com/seto77/ReciPro/assets/524585/50d1e8b8-e772-4fe5-a56d-c644525a4262)
The distance is also "kind of" available with the live readout of the position of the cursor and after double clicking an individual spot.
Also, could the length of the vector would also be a nice information to be displayed in that window.

And of course I want to use the chance to thank you for this amazing piece of software!

**Comment by seto77** [comment]
Thanks for the nice request.
Please try ver4.863.
![image](https://github.com/seto77/ReciPro/assets/44538886/aba052e2-f5b6-4bbc-89e2-d8762b09cc6c)

**Comment by seto77** [comment]
Thanks for the nice request.
Please try ver4.864.
![image](https://github.com/seto77/ReciPro/assets/44538886/aba052e2-f5b6-4bbc-89e2-d8762b09cc6c)

**Comment by rbtrrnss** [comment]
Great, this was a VERY quick response and addition! It works great!
Generally I would also be interested in having this exact value (nm^-1) displayed for all diffraction spots (similar to the d-spacing or Index as it is available on the bottom of the window of the diffraction simulator.

**Comment by seto77** [comment]
Please check the "1/d" item next to the "d". I hope it helps you in your research.
![image](https://github.com/seto77/ReciPro/assets/44538886/676b5b57-2944-4c08-938e-160a9edc92a5)

**Comment by rbtrrnss** [comment]
I'll close the issue now.
