### ISSUE TITLE
HRTEM/STEM Simulator: config sidebar not fully visible

### ISSUE THREAD

**Issue by JingshanDu** [seto77/ReciPro#29]
The sidebar in the HRTEM/STEM Simulator contains important configurational inputs. However, in the latest version, the sidebar is only partially visible. I tried to drag its edge, but it does not expand the sidebar either. 

<img width="890" alt="Screenshot 2024-03-05 020707" src="https://github.com/seto77/ReciPro/assets/18127983/7ea353d9-1438-4674-86f7-d2cc6eb3aee2">

**Comment by seto77** [comment]
Thank you very much for reporting the bug. The GUI design seems to have gone wrong.
Please try the latest version (ver4.879), in which the division boundary can be moved.

**Comment by JingshanDu** [comment]
Wow thank you so much for responding and fixing the problem so rapidly, @seto77-san! I'm really impressed! :)
I test v 4.879, and the sidebar can be expanded correctly.
