### ISSUE TITLE
Blank page in the diffraction simulator

### ISSUE THREAD

**Issue by yijecho** [seto77/ReciPro#3]
I wonder why I am only seeing the blank page (black) in the diffraction simulator. I selected the material from the crystal list, but it showed nothing.

![image](https://user-images.githubusercontent.com/63065018/94117200-efdb8500-fe19-11ea-9c36-6da81f1d4c16.JPG)

**Comment by seto77** [comment]
I think you're zooming in too much. You can zoom out by mouse left-click on the main area.

Also, check the energy of the incident wave in "Wave" tab (upperleft). For X-ray, about 1-100 kev is appropriate. For electron, about 10-1000 kev is appropriate.
