### ISSUE TITLE
Returned csv header from Marco's `ReciPro.DifSim.SpotInfo()` always lists "Ug" etc. regardless of the "Vg [eV]" option (while the values are indeed Vg)

### ISSUE THREAD

**Issue by tianyu-liu** [seto77/ReciPro#34]
As the title suggests, when the "Unit of poteintial" is set to "Vg [eV]", the `ReciPro.DifSim.SpotInfo()` function in Marco still has "Ug" etc in the returned csv header, although the values will actually be Vg values.

On the other hand, when using the "Copy to clipboard" button from GUI, the returned text has the correct "Vg" in header, accordingly.

BTW, a typo in "Unit of **poteintial**".

On version 4.884.

Cheers

![image](https://github.com/seto77/ReciPro/assets/10370139/917b822e-68b7-4685-ac62-79be9d2ae26c)

**Comment by seto77** [comment]
Thank you for your very kind bug report.
I have released a fixed version; please try v.4.885.
