### ISSUE TITLE
Specify zone axis in macro

### ISSUE THREAD

**Issue by ericpre** [seto77/ReciPro#37]
Is there a macro command to specify the zone axis?

Thank you! :)

**Comment by seto77** [comment]
You mean, is there a macro command that makes the specified zone axis normal to the screen?
There was no such macro command in previous versions, so I have added them to the new version (v.4.892).
![image](https://github.com/user-attachments/assets/20783947-8cfa-4aaa-93b6-a9204e8817fd)
The following are two new commands.
- ReciPro.Dir.ProjectAlongAxis(u, v, w)
- ReciPro.Dir.ProjectAlongPlane(h, k, l)

Does it meet your needs?

**Comment by ericpre** [comment]
Yes, this is very useful, thank you!
