### ISSUE TITLE
Bug: Diffraction Simulator - Draw Spots With Same Radius

### ISSUE THREAD

**Issue by lukmuk** [seto77/ReciPro#40]
Hello seto-san,

after updating ReciPro from version 4.883 (working) to 4.892 (bug), I noticed that the "**Draw all spots with the same radius**" option seems to be not working anymore (see images below). 
I have not checked the versions between these two, so I have not pinpointed when exactly this bug was introduced.

I hope this report helps to find the issue. Thank you for your efforts!

Kind regards,
lukmuk

Working as expected, all spots with same radius (4.883):
![working](https://github.com/user-attachments/assets/c705bf3a-e55d-45ae-85e1-89444e2b8bb4)

Not working, spots with different radius (4.892):
![bug](https://github.com/user-attachments/assets/25e1b2a9-dd75-40d6-af7c-a918800d7b8a)

**Comment by seto77** [comment]
Thank you for reporting the bug!
This issue has been fixed in the new version (v.4.893).
Try it please!

**Comment by lukmuk** [comment]
Works great, thank you for the quick fix! 😊
